version: '3.0'
services:
  rasa:
    image: rasa/rasa:3.6.6-full
    ports:
      - 5005:5005
    volumes:
      - .:/app
    command: run -m models --enable-api --cors "*"
  action-server:
    image: rasa/rasa:3.6.6-full
    volumes:
      - ./actions:/app/actions
    ports:
      - 5055:5055